ExercicioCadastro/Models/Aluno.cs
using System.ComponentModel.DataAnnotations;

namespace ExercicioCadastro.Models
{
    public class Aluno
    {
        [Key]
        public int MatriculaId {get; set;}
        public string Nome {get; set;}
        public string Sobrenome {get; set;}
        public string Cpf {get; set;}
        public string Curso {get; set;}
    }
}

ExercicioCadastro/Models/ErrorViewModel.cs
using System;

namespace ExercicioCadastro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExercicioCadastro/Controllers/AlunoController.cs
using System;
using System.Linq;
using ExercicioCadastro.Database;
using ExercicioCadastro.Models;
using Microsoft.AspNetCore.Mvc;


namespace ExercicioCadastro.Controllers
{

    public class AlunoController : Controller
    {

    private readonly ApplicationDbContext database;    

    public AlunoController(ApplicationDbContext database)
    {
        this.database = database;
    }

        public IActionResult Index()
        {
            var aluno = database.Alunos.ToList();
            return View(aluno);
        }


        public IActionResult Cadastrar()
        {
            return View();
        }

       public IActionResult Editar(int id)
        {
        	Aluno aluno = database.Alunos.First(register => register.MatriculaId == id);
	        return View("Cadastrar", aluno); 
        }



        [HttpPost]
        public IActionResult Salvar(Aluno aluno){
        if(aluno.MatriculaId == 0)
        {
            database.Alunos.Add(aluno);
            }
        else{
            Aluno alunoDoBanco = database.Alunos.First(registro => registro.MatriculaId == aluno.MatriculaId);
            }
        {
            database.Alunos.Add(aluno);
            database.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

ExercicioCadastro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ExercicioCadastro.Models;
using ExercicioCadastro.Database;

namespace ExercicioCadastro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
   
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExercicioCadastro/Views/Aluno/Cadastrar.cshtml
@model ExercicioCadastro.Models.Aluno

<h2>Cadastro de Alunos </h2>

<form class="form-horizontal" asp-controller="Aluno" asp-action="Salvar" method="POST">
    <input type="hidden" asp-for="MatriculaId" placeholder="Nome">
    <input type="text" class="form-control" asp-for="Nome" placeholder="Nome">
    <input type="text" class="form-control" asp-for="Sobrenome" placeholder="Sobrenome">
    <input type="text" class="form-control" asp-for="Cpf" placeholder="CPF">
    <input type="text" class="form-control" asp-for="Curso" placeholder="Curso">
    <button class="btn btn-success">Cadastrar</button>

</form>

ExercicioCadastro/Views/Aluno/Index.cshtml
@model IEnumerable<ExercicioCadastro.Models.Aluno>

<h2>Todos os Alunos</h2>

<a href="/Aluno/Cadastrar" class="btn btn-success">Novo aluno</a>

@foreach(var aluno in Model) 
{
    <p>Nome: @aluno.Nome</p>
    <p>Sobrenome: @aluno.Sobrenome</p>
    <p>CPF: @aluno.Cpf</p>
    <p>Curso: @aluno.Curso</p>
    <a href="/Aluno/Editar/@aluno.MatriculaId" class="btn btn-success">Editar</a>
    <hr>
}

ExercicioCadastro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExercicioCadastro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExercicioCadastro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExercicioCadastro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ExercicioCadastro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>